<?php

namespace paOnde\backendBundle\Repository;

/**
 * Office_tagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Office_tagsRepository extends \Doctrine\ORM\EntityRepository
{
}
