<?php

namespace paOnde\backendBundle\Repository;

/**
 * Social_netRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Social_netRepository extends \Doctrine\ORM\EntityRepository
{
}
