<?php

namespace paOnde\backendBundle\Repository;

/**
 * Tags_cloudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tags_cloudRepository extends \Doctrine\ORM\EntityRepository
{
}
