<?php

namespace Zahira\ZahiraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhRepository extends EntityRepository
{
    public function viewRh(){
        $em = $this->getEntityManager();
        $dql = 'SELECT '
                    .'rh.codRh, '
                    .'rh.tipoRh '
                .'FROM zahiraBundle:Rh rh ';
        $query = $em->createQuery($dql);
        $result = $query->getResult();
        return $result;
    }
}
