<?php

namespace Zahira\ZahiraBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Zahira\ZahiraBundle\Entity\Eps;

/**
 * youthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class youthRepository extends EntityRepository
{
    
    public function counterUser() {
         $em = $this->getEntityManager();
         $dql = 'SELECT count(juven.id) FROM zahiraBundle:youth juven WHERE juven.stateYouth = true';
         $query = $em->createQuery($dql);
         $result = $query->getResult();
         
        return $result;
    }
    
    // funcion get para listar unos datos de los usuarios y tambien para list
    public function GetYouth() {
        $em = $this->getEntityManager();
        $dql = 'SELECT '
                    .'juven.id, '
                    .'juven.codYouth, '
                    .'juven.nameYouth, '
                    .'juven.lastnameYouth, '
                    .'juven.phoneYouth, '
                    .'juven.addressYouth, '
                    .'juven.bingoYouth, '
                    .'juven.stateYouth, '
                    .'juven.imageYouth '
                .'FROM zahiraBundle:youth juven '
                .'WHERE juven.stateYouth = true '
                . 'ORDER BY juven.nameYouth';
        $query = $em->createQuery($dql);
        $result = $query->getResult();
        
        return $result;
    }
    
    
    public function ViewYouth($id){
        $em = $this->getEntityManager();
        $dql = 'SELECT '
                    .'juven.codYouth, '
                    .'juven.nameYouth, '
                    .'juven.lastnameYouth, '
                    .'juven.birthdate, '
                    .'juven.groupYouth, '
                    .'juven.addressYouth, '
                    .'juven.phoneYouth, '
                    .'juven.mailYouth, '
                    .'juven.commune, '
                    .'juven.imageYouth, '
                    .'juven.registerYouth, '
                    .'juven.stateYouth, '
                    .'juven.sexYouth, '
                    .'juven.voteYouth, '
                    .'juven.subsidy, '
                    .'juven.pensionYouth, '
                    .'juven.entityYouth, '
                    .'juven.sisbenYouth, '
                    .'juven.bingoYouth, '
                    .'juven.sizeYouth, '

                    .'eps.nameEps, '
                    .'eps.regimeEps, '
                
                    .'rh.tipoRh '
                
                .'FROM zahiraBundle:youth juven '
                .'JOIN zahiraBundle:Eps AS eps WITH juven.codEps = eps.codEps '
                .'JOIN zahiraBundle:Rh AS rh WITH juven.cod_Rh = rh.codRh '
                .'WHERE juven.id = '. $id
                .' AND juven.stateYouth = true '
                . 'ORDER BY juven.nameYouth';
        $query = $em->createQuery($dql);
        $result = $query->getResult();

        return $result;
    }
    
    
    //funcion para borrar logicamente un usuario
    
    public function DeleteLogYouth($id) {
        $em = $this->getEntityManager();
        $dql = 'UPDATE '
                    .'zahiraBundle:youth juven '
                    .'SET '
                    .'juven.stateYouth = false '
                .'WHERE juven.id = '. $id;
        $query = $em->createQuery($dql);
        $result = $query->getResult();
        return $result; 
    }
}
